#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_okta="$(aws-okta version 2>/dev/null | awk '{print $2}' | sed 's#^v##' || true)"
  jq -n --arg okta "$ver_okta" '{okta: $okta}'
}

version "$@"
